apiVersion: v1
kind: Pod
metadata:
  name: mypod
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "kubernetes.io/hostname"
                  operator: In
                  values:
                    - node1
      containers:
        - name: mycontainer
          image: nginx
