apiVersion: v1
kind: Pod
metadata:
  name: pod-ejemplo
  labels:
    app: ejemplo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - ssd
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "workload"
      effect: "NoSchedule"
  containers:
    - name: nginx
      image: nginx:latest