apiVersion: v1
kind: Pod
metadata:
  name: rook-ceph-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /mnt/data
          name: rook-storage
  volumes:
    - name: rook-storage
      persistentVolumeClaim:
        claimName: rook-ceph-pvc