apiVersion: v1 # Esta es la versión de la API de Kubernetes que vamos a usar
kind: Service # Vamos a crear un servicio
metadata: # Metadatos del servicio
  name: nginx-service # Nombre del servicio
  labels: # Etiquetas del servicio
    app: nginx # Etiqueta app con valor nginx
spec: # Especificaciones del servicio
  type: NodePort # Tipo de servicio
  selector: # Selector de los pods que vamos a exponer
    app: nginx # Etiqueta app con valor nginx para exponer los pods con esta etiqueta que configuramos previamente en mi nginx-deployment.yaml
  ports: # Puertos del servicio
  - protocol: TCP # Protocolo TCP
    port: 80 # Puerto 80 del servicio
    targetPort: 80 # Puerto 80 del pod
    nodePort: 30006 # Puerto del nodo

